[project]
name = "source-seeking-optimization"
version = "0.1.0"
description = "Source seeking and optimization of swarm algorithms for multi-agents"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=2.2.5",
    "ruff>=0.11.8",
]
